### ISSUE TITLE
Link to Shortcuts script just links to Apple Store

### ISSUE THREAD

**Issue by brandonhaslegs** [PsiPhiTheta/GoogleMaps-2-AppleMaps#3]
Clicking "Get shortcut" from this page https://www.icloud.com/shortcuts/b70812c989a148d084b070ef4772988e just takes me to the iOS Shortcuts App download page.

**Comment by brandonhaslegs** [comment]
You should make it clear you need to open this link on your iPhone, you can't open it on your Mac.

**Comment by PsiPhiTheta** [comment]
Dupe of #1
